### ISSUE TITLE
wvd and cookies are in directory still

### ISSUE THREAD

**Issue by rahulbanwasi** [bdim404/music-download-telegram-bot#2]
Traceback (most recent call last):
  File "/home/ubuntu/abo/src/main.py", line 5, in <module>
    from apple_music_checker import AppleMusicChecker
  File "/home/ubuntu/abo/src/apple_music_checker.py", line 20, in <module>
    downloader = Downloader()
  File "/home/ubuntu/abo/src/apple_music_downloader.py", line 53, in __init__
    self.wvd_location = Path(WVD_LOCATION)
  File "/usr/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by bdim404** [comment]
Have you check your .wvd files location info in .env?

**Comment by bdim404** [comment]
Delete your telegram bot token in your comment first, and i will check this problem.

**Comment by bdim404** [comment]
Your all problems have been fixed in https://github.com/bdim404/music-download-telegram-bot/commit/5dac1a8b14e106a66673a1e2df0ef52bb2525843.
We support download the songs in only one link at a time now.
